int16 USE_XY_PLANE = 1
int16 USE_XZ_PLANE = 2
int16 USE_YZ_PLANE = 3
int16 TOGGLE_PLANE = 4
int16 INCREASE_LINEAR_VELOCITY = 5
int16 DECREASE_LINEAR_VELOCITY = 6
int16 INCREASE_ANGULAR_VELOCITY = 7
int16 DECREASE_ANGULAR_VELOCITY = 8
int16 TOGGLE_CONTROLLER = 9
int16 TOGGLE_WORLD_AND_TCP_FRAME = 10

int16[] pressed_commands
---
bool success
string error_msg