string USE_XY_PLANE = XY_PLANE
string USE_XZ_PLANE = XZ_PLANE
string USE_YZ_PLANE = YZ_PLANE
string TOGGLE_PLANE = TOGGLE_PLANE
string INCREASE_LINEAR_VELOCITY = INCREASE_LINEAR_VELOCITY
string DECREASE_LINEAR_VELOCITY = DECREASE_LINEAR_VELOCITY
string INCREASE_ANGULAR_VELOCITY = INCREASE_ANGULAR_VELOCITY
string DECREASE_ANGULAR_VELOCITY = DECREASE_ANGULAR_VELOCITY
string TOGGLE_CONTROLLER = TOGGLE_CONTROLLER
string TOGGLE_TARGET_FRAME = TOGGLE_TARGET_FRAME
string TOGGLE_JOINT_DOWN = TOGGLE_JOINT_DOWN
string TOGGLE_JOINT_UP = TOGGLE_JOINT_UP

string[] pressed_commands
---
bool success
string error_msg