MovementBindings:
  'q': {linear: {x: 1}}
  'a': {linear: {x: -1}}
  'w': {linear: {y: 1}}
  's': {linear: {y: -1}}
  'e': {linear: {z: 1}}
  'd': {linear: {z: -1}}
  'Q': {angular: {x: 1}}
  'A': {angular: {x: -1}}
  'W': {angular: {y: 1}}
  'S': {angular: {y: -1}}
  'E': {angular: {z: 1}}
  'D': {angular: {z: -1}}
JointJogBindings:
  'z': {"joint_names": ["prbt_joint_1"], "velocities": [1]}
  'h': {"joint_names": ["prbt_joint_1"], "velocities": [-1]}
  'u': {"joint_names": ["prbt_joint_2"], "velocities": [1]}
  'j': {"joint_names": ["prbt_joint_2"], "velocities": [-1]}
  'i': {"joint_names": ["prbt_joint_3"], "velocities": [1]}
  'k': {"joint_names": ["prbt_joint_3"], "velocities": [-1]}
  'o': {"joint_names": ["prbt_joint_4"], "velocities": [1]}
  'l': {"joint_names": ["prbt_joint_4"], "velocities": [-1]}
  'p': {"joint_names": ["prbt_joint_5"], "velocities": [1]}
  'ö': {"joint_names": ["prbt_joint_5"], "velocities": [-1]}
  'ü': {"joint_names": ["prbt_joint_6"], "velocities": [1]}
  'ä': {"joint_names": ["prbt_joint_6"], "velocities": [-1]}
SettingBindings:
  '1': "INCREASE_LINEAR_VELOCITY"
  '2': "DECREASE_LINEAR_VELOCITY"
  '4': "INCREASE_ANGULAR_VELOCITY"
  '5': "DECREASE_ANGULAR_VELOCITY"
  'KEY_UP': "INCREASE_LINEAR_VELOCITY"
  'KEY_DOWN': "DECREASE_LINEAR_VELOCITY"
  'KEY_RIGHT': "INCREASE_ANGULAR_VELOCITY"
  'KEY_LEFT': "DECREASE_ANGULAR_VELOCITY"
  ' ': "TOGGLE_TARGET_FRAME"
Description: |-
  - 'q' 'w' 'e' = x+ y+ z+
  - 'a' 's' 'd' = x- y- z-
  - 'z' 'u' 'i' 'o' 'p' 'ue' = [joint1 - joint 6] + 
  - 'h' 'j' 'k' 'l' 'oe' 'ae' = [joint1 - joint 6] -
  - '1' / '2' = Linear Speed + / -
  - 'UP' / 'DOWN' = Linear Speed + / -
  - '3' / '4' = Angular Speed + / -
  - 'RIGHT' / 'LEFT' = Angular Speed + / -
